# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
  # Example:
  # password: {{ .Values.password | b64enc }}
# stringData:
#   username: admin      # required field for kubernetes.io/basic-auth
#   password: t0p-Secret # required field for kubernetes.io/basic-auth
# immutable: true

